/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function isUppercase(char: string): boolean
export function splitByCase(str: string): string
export function pascalCase(str: string): string
